name: secret
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  echo:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: echo
        run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
